version: '3.4'

services:
  web:
    container_name: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      default:
        ipv4_address: 172.22.136.197
    ports:
      - "80"


networks:
  default:
    external:
      name: nat
