version: '3.4'

services:
  db:
    container_name: db
    image: microsoft/mssql-server-windows-express
    networks:
      default:
        ipv4_address: 172.22.136.195
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Alaska2017
      - ACCEPT_EULA=Y
  wcf:
    container_name: wcf
    image: wcfservice:self-hosted
    networks:
      default:
       ipv4_address: 172.22.136.196
    depends_on:
      - db

networks:
  default:
    external:
      name: nat
